##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - clang
    - clang-tools
    - cppcheck
    - debhelper
    - git
    - expect #required for unbuffer
    - gnome-pkg-tools
    - gobject-introspection
    - libgtk-3-dev
    - libgtk-3-doc
    - libatk1.0-dev
    - libxml2-dev
    - libxml2-utils
    - pkg-config
    - intltool
    - gtk-doc-tools
    - libgdk-pixbuf2.0-doc
    - libglib2.0-dev
    - libglib2.0-doc
    - libgladeui-dev
    - libgirepository1.0-dev
    - libpango1.0-doc
    - make
    - valac
    - xauth
    - xvfb

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
